scss_files: 'src/assets/scss/**/*.scss'

linters:
  SingleLinePerSelector:
    enabled: false

  ImportantRule:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  VendorPrefix:
    enabled: false

  IdSelector:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  DeclarationOrder:
    enabled: false

  StringQuotes:
    enabled: false

  NameFormat:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  SelectorFormat:
    enabled: false

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: false
